# Generated by Django 6.0.7 on 2026-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consistency_bio_and_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
