# Generated by Django 6.0.8 on 2026-09-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pending_email_expiry_and_bio_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Shut down by an administrator. Blocks every way back in, including Google sign-in.'),
        ),
    ]
