# Generated by Django 6.0.8 on 2026-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
